/*Components*/
import CarouselBanner from "@/components/CarouselBanner";

const HomeContainer = ({ data }) => {
	return (
		<div>
			<CarouselBanner items={data} />
			<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ornare dolor ut risus cursus placerat. Aenean venenatis turpis odio, at iaculis arcu ornare sed. Phasellus feugiat lacinia urna at venenatis. Curabitur quis ipsum eleifend, euismod sem sit amet, pharetra turpis. Curabitur et eros nec justo rhoncus pharetra at sit amet massa. Vivamus condimentum urna et mauris eleifend, in viverra massa varius. Phasellus nec aliquet eros. Sed et nisi vitae nisl convallis accumsan. Etiam egestas mattis ligula non mattis. Nunc scelerisque mattis arcu, condimentum ornare lacus rutrum vel. Nunc imperdiet, libero a pulvinar maximus, eros elit interdum arcu, vitae venenatis purus mauris vitae odio. Pellentesque id orci sed orci eleifend tempus eu ac massa. Curabitur sed odio nisi. Fusce eu suscipit ex, ut ullamcorper ipsum. Sed condimentum elit sed felis aliquet, quis vestibulum mi molestie. Praesent condimentum velit eget imperdiet convallis.

In porttitor libero a tellus venenatis semper eget ut nisl. Donec id maximus elit. Nulla sit amet sollicitudin elit. Fusce ac lacinia nulla. Vivamus vestibulum sit amet urna eu porttitor. Praesent efficitur orci sed massa consectetur egestas. Proin id sapien id nibh ultricies dictum a eu lectus. Sed nec ullamcorper erat. Donec odio nisl, congue non odio a, aliquam accumsan libero. Pellentesque quis sapien orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sagittis, quam in mattis iaculis, ipsum risus pellentesque odio, ut semper neque justo nec purus. Sed faucibus erat ut erat gravida volutpat non at nisi.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ornare dolor ut risus cursus placerat. Aenean venenatis turpis odio, at iaculis arcu ornare sed. Phasellus feugiat lacinia urna at venenatis. Curabitur quis ipsum eleifend, euismod sem sit amet, pharetra turpis. Curabitur et eros nec justo rhoncus pharetra at sit amet massa. Vivamus condimentum urna et mauris eleifend, in viverra massa varius. Phasellus nec aliquet eros. Sed et nisi vitae nisl convallis accumsan. Etiam egestas mattis ligula non mattis. Nunc scelerisque mattis arcu, condimentum ornare lacus rutrum vel. Nunc imperdiet, libero a pulvinar maximus, eros elit interdum arcu, vitae venenatis purus mauris vitae odio. Pellentesque id orci sed orci eleifend tempus eu ac massa. Curabitur sed odio nisi. Fusce eu suscipit ex, ut ullamcorper ipsum. Sed condimentum elit sed felis aliquet, quis vestibulum mi molestie. Praesent condimentum velit eget imperdiet convallis.

In porttitor libero a tellus venenatis semper egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ornare dolor ut risus cursus placerat. Aenean venenatis turpis odio, at iaculis arcu ornare sed. Phasellus feugiat lacinia urna at venenatis. Curabitur quis ipsum eleifend, euismod sem sit amet, pharetra turpis. Curabitur et eros nec justo rhoncus pharetra at sit amet massa. Vivamus condimentum urna et mauris eleifend, in viverra massa varius. Phasellus nec aliquet eros. Sed et nisi vitae nisl convallis accumsan. Etiam egestas mattis ligula non mattis. Nunc scelerisque mattis arcu, condimentum ornare lacus rutrum vel. Nunc imperdiet, libero a pulvinar maximus, eros elit interdum arcu, vitae venenatis purus mauris vitae odio. Pellentesque id orci sed orci eleifend tempus eu ac massa. Curabitur sed odio nisi. Fusce eu suscipit ex, ut ullamcorper ipsum. Sed condimentum elit sed felis aliquet, quis vestibulum mi molestie. Praesent condimentum velit eget imperdiet convallis.

In porttitor libero a tellus venenatis semper egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ornare dolor ut risus cursus placerat. Aenean venenatis turpis odio, at iaculis arcu ornare sed. Phasellus feugiat lacinia urna at venenatis. Curabitur quis ipsum eleifend, euismod sem sit amet, pharetra turpis. Curabitur et eros nec justo rhoncus pharetra at sit amet massa. Vivamus condimentum urna et mauris eleifend, in viverra massa varius. Phasellus nec aliquet eros. Sed et nisi vitae nisl convallis accumsan. Etiam egestas mattis ligula non mattis. Nunc scelerisque mattis arcu, condimentum ornare lacus rutrum vel. Nunc imperdiet, libero a pulvinar maximus, eros elit interdum arcu, vitae venenatis purus mauris vitae odio. Pellentesque id orci sed orci eleifend tempus eu ac massa. Curabitur sed odio nisi. Fusce eu suscipit ex, ut ullamcorper ipsum. Sed condimentum elit sed felis aliquet, quis vestibulum mi molestie. Praesent condimentum velit eget imperdiet convallis.

In porttitor libero a tellus venenatis semper egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ornare dolor ut risus cursus placerat. Aenean venenatis turpis odio, at iaculis arcu ornare sed. Phasellus feugiat lacinia urna at venenatis. Curabitur quis ipsum eleifend, euismod sem sit amet, pharetra turpis. Curabitur et eros nec justo rhoncus pharetra at sit amet massa. Vivamus condimentum urna et mauris eleifend, in viverra massa varius. Phasellus nec aliquet eros. Sed et nisi vitae nisl convallis accumsan. Etiam egestas mattis ligula non mattis. Nunc scelerisque mattis arcu, condimentum ornare lacus rutrum vel. Nunc imperdiet, libero a pulvinar maximus, eros elit interdum arcu, vitae venenatis purus mauris vitae odio. Pellentesque id orci sed orci eleifend tempus eu ac massa. Curabitur sed odio nisi. Fusce eu suscipit ex, ut ullamcorper ipsum. Sed condimentum elit sed felis aliquet, quis vestibulum mi molestie. Praesent condimentum velit eget imperdiet convallis.

In porttitor libero a tellus venenatis semper egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ornare dolor ut risus cursus placerat. Aenean venenatis turpis odio, at iaculis arcu ornare sed. Phasellus feugiat lacinia urna at venenatis. Curabitur quis ipsum eleifend, euismod sem sit amet, pharetra turpis. Curabitur et eros nec justo rhoncus pharetra at sit amet massa. Vivamus condimentum urna et mauris eleifend, in viverra massa varius. Phasellus nec aliquet eros. Sed et nisi vitae nisl convallis accumsan. Etiam egestas mattis ligula non mattis. Nunc scelerisque mattis arcu, condimentum ornare lacus rutrum vel. Nunc imperdiet, libero a pulvinar maximus, eros elit interdum arcu, vitae venenatis purus mauris vitae odio. Pellentesque id orci sed orci eleifend tempus eu ac massa. Curabitur sed odio nisi. Fusce eu suscipit ex, ut ullamcorper ipsum. Sed condimentum elit sed felis aliquet, quis vestibulum mi molestie. Praesent condimentum velit eget imperdiet convallis.

In porttitor libero a tellus venenatis semper egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ornare dolor ut risus cursus placerat. Aenean venenatis turpis odio, at iaculis arcu ornare sed. Phasellus feugiat lacinia urna at venenatis. Curabitur quis ipsum eleifend, euismod sem sit amet, pharetra turpis. Curabitur et eros nec justo rhoncus pharetra at sit amet massa. Vivamus condimentum urna et mauris eleifend, in viverra massa varius. Phasellus nec aliquet eros. Sed et nisi vitae nisl convallis accumsan. Etiam egestas mattis ligula non mattis. Nunc scelerisque mattis arcu, condimentum ornare lacus rutrum vel. Nunc imperdiet, libero a pulvinar maximus, eros elit interdum arcu, vitae venenatis purus mauris vitae odio. Pellentesque id orci sed orci eleifend tempus eu ac massa. Curabitur sed odio nisi. Fusce eu suscipit ex, ut ullamcorper ipsum. Sed condimentum elit sed felis aliquet, quis vestibulum mi molestie. Praesent condimentum velit eget imperdiet convallis.

In porttitor libero a tellus venenatis semper eget
		</div></div>
	)
}

export default HomeContainer